/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as IndexImport } from "./routes/index";
import { Route as ManagementHierarchyImport } from "./routes/management/hierarchy";
import { Route as ActivitiesOnlineCoursesIndexImport } from "./routes/activities/online-courses/index";

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

const ManagementHierarchyRoute = ManagementHierarchyImport.update({
  id: "/management/hierarchy",
  path: "/management/hierarchy",
  getParentRoute: () => rootRoute,
} as any);

const ActivitiesOnlineCoursesIndexRoute =
  ActivitiesOnlineCoursesIndexImport.update({
    id: "/activities/online-courses/",
    path: "/activities/online-courses/",
    getParentRoute: () => rootRoute,
  } as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/management/hierarchy": {
      id: "/management/hierarchy";
      path: "/management/hierarchy";
      fullPath: "/management/hierarchy";
      preLoaderRoute: typeof ManagementHierarchyImport;
      parentRoute: typeof rootRoute;
    };
    "/activities/online-courses/": {
      id: "/activities/online-courses/";
      path: "/activities/online-courses";
      fullPath: "/activities/online-courses";
      preLoaderRoute: typeof ActivitiesOnlineCoursesIndexImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/management/hierarchy": typeof ManagementHierarchyRoute;
  "/activities/online-courses": typeof ActivitiesOnlineCoursesIndexRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/management/hierarchy": typeof ManagementHierarchyRoute;
  "/activities/online-courses": typeof ActivitiesOnlineCoursesIndexRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/management/hierarchy": typeof ManagementHierarchyRoute;
  "/activities/online-courses/": typeof ActivitiesOnlineCoursesIndexRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/management/hierarchy" | "/activities/online-courses";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/management/hierarchy" | "/activities/online-courses";
  id:
    | "__root__"
    | "/"
    | "/management/hierarchy"
    | "/activities/online-courses/";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ManagementHierarchyRoute: typeof ManagementHierarchyRoute;
  ActivitiesOnlineCoursesIndexRoute: typeof ActivitiesOnlineCoursesIndexRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ManagementHierarchyRoute: ManagementHierarchyRoute,
  ActivitiesOnlineCoursesIndexRoute: ActivitiesOnlineCoursesIndexRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/management/hierarchy",
        "/activities/online-courses/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/management/hierarchy": {
      "filePath": "management/hierarchy.tsx"
    },
    "/activities/online-courses/": {
      "filePath": "activities/online-courses/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
